CSEXPORT csbool CSCONV Export_FBuildGlobals_UE_BUILD_DEBUG()
{
	return UE_BUILD_DEBUG;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_UE_BUILD_DEVELOPMENT()
{
	return UE_BUILD_DEVELOPMENT;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_UE_BUILD_TEST()
{
	return UE_BUILD_TEST;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_UE_BUILD_SHIPPING()
{
	return UE_BUILD_SHIPPING;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_UE_GAME()
{
	return UE_GAME;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_UE_EDITOR()
{
	return UE_EDITOR;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_UE_SERVER()
{
	return UE_SERVER;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_WITH_EDITOR()
{
	return WITH_EDITOR;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_WITH_ENGINE()
{
	return WITH_ENGINE;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_WITH_UNREAL_DEVELOPER_TOOLS()
{
	return WITH_UNREAL_DEVELOPER_TOOLS;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_WITH_PLUGIN_SUPPORT()
{
	return WITH_PLUGIN_SUPPORT;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_WITH_PERFCOUNTERS()
{
	return WITH_PERFCOUNTERS;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_HACK_HEADER_GENERATOR()
{
	return HACK_HEADER_GENERATOR;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_WITH_AUTOMATION_WORKER()
{
	return WITH_AUTOMATION_WORKER;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_UE_BUILD_MINIMAL()
{
	return UE_BUILD_MINIMAL;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_IS_MONOLITHIC()
{
	return IS_MONOLITHIC;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_IS_PROGRAM()
{
	return IS_PROGRAM;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_WITH_HOT_RELOAD()
{
	return WITH_HOT_RELOAD;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_CHECK_PUREVIRTUALS()
{
	return CHECK_PUREVIRTUALS;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_USE_NULL_RHI()
{
	return USE_NULL_RHI;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_USE_LOGGING_IN_SHIPPING()
{
	return USE_LOGGING_IN_SHIPPING;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_USE_CHECKS_IN_SHIPPING()
{
	return USE_CHECKS_IN_SHIPPING;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_DO_GUARD_SLOW()
{
	return DO_GUARD_SLOW;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_DO_CHECK()
{
	return DO_CHECK;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_STATS()
{
	return STATS;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_ALLOW_DEBUG_FILES()
{
	return ALLOW_DEBUG_FILES;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_NO_LOGGING()
{
	return NO_LOGGING;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_LOOKING_FOR_PERF_ISSUES()
{
	return LOOKING_FOR_PERF_ISSUES;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_USE_NETWORK_PROFILER()
{
	return USE_NETWORK_PROFILER;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_USE_UBER_GRAPH_PERSISTENT_FRAME()
{
	return USE_UBER_GRAPH_PERSISTENT_FRAME;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_UE_BLUEPRINT_EVENTGRAPH_FASTCALLS()
{
	return UE_BLUEPRINT_EVENTGRAPH_FASTCALLS;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_USE_SERVER_PERF_COUNTERS()
{
	return USE_SERVER_PERF_COUNTERS;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_USE_CIRCULAR_DEPENDENCY_LOAD_DEFERRING()
{
	return USE_CIRCULAR_DEPENDENCY_LOAD_DEFERRING;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_USE_DEFERRED_DEPENDENCY_CHECK_VERIFICATION_TESTS()
{
	return USE_DEFERRED_DEPENDENCY_CHECK_VERIFICATION_TESTS;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_ALLOW_PROFILEGPU_IN_TEST()
{
	return ALLOW_PROFILEGPU_IN_TEST;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_WITH_PROFILEGPU()
{
	return WITH_PROFILEGPU;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_WITH_METADATA()
{
	return WITH_METADATA;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_WITH_SERVER_CODE()
{
	return WITH_SERVER_CODE;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_WITH_EDITORONLY_DATA()
{
	return WITH_EDITORONLY_DATA;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_WITH_COREUOBJECT()
{
	return WITH_COREUOBJECT;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_USE_STATS_WITHOUT_ENGINE()
{
	return USE_STATS_WITHOUT_ENGINE;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_WITH_LOGGING_TO_MEMORY()
{
	return WITH_LOGGING_TO_MEMORY;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_USE_CACHE_FREED_OS_ALLOCS()
{
	return USE_CACHE_FREED_OS_ALLOCS;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_WITH_CEF3()
{
	return WITH_CEF3;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_WITH_XGE_CONTROLLER()
{
	return WITH_XGE_CONTROLLER;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_WITH_DEV_AUTOMATION_TESTS()
{
	return WITH_DEV_AUTOMATION_TESTS;
}

CSEXPORT csbool CSCONV Export_FBuildGlobals_WITH_PERF_AUTOMATION_TESTS()
{
	return WITH_PERF_AUTOMATION_TESTS;
}

CSEXPORT int32 CSCONV Export_FBuildGlobals_ENGINE_MAJOR_VERSION()
{
	return ENGINE_MAJOR_VERSION;
}

CSEXPORT int32 CSCONV Export_FBuildGlobals_ENGINE_MINOR_VERSION()
{
	return ENGINE_MINOR_VERSION;
}

CSEXPORT int32 CSCONV Export_FBuildGlobals_ENGINE_PATCH_VERSION()
{
	return ENGINE_PATCH_VERSION;
}

CSEXPORT void CSCONV Export_FBuildGlobals(RegisterFunc registerFunc)
{
	REGISTER_FUNC(Export_FBuildGlobals_UE_BUILD_DEBUG);
	REGISTER_FUNC(Export_FBuildGlobals_UE_BUILD_DEVELOPMENT);
	REGISTER_FUNC(Export_FBuildGlobals_UE_BUILD_TEST);
	REGISTER_FUNC(Export_FBuildGlobals_UE_BUILD_SHIPPING);
	REGISTER_FUNC(Export_FBuildGlobals_UE_GAME);
	REGISTER_FUNC(Export_FBuildGlobals_UE_EDITOR);
	REGISTER_FUNC(Export_FBuildGlobals_UE_SERVER);
	REGISTER_FUNC(Export_FBuildGlobals_WITH_EDITOR);
	REGISTER_FUNC(Export_FBuildGlobals_WITH_ENGINE);
	REGISTER_FUNC(Export_FBuildGlobals_WITH_UNREAL_DEVELOPER_TOOLS);
	REGISTER_FUNC(Export_FBuildGlobals_WITH_PLUGIN_SUPPORT);
	REGISTER_FUNC(Export_FBuildGlobals_WITH_PERFCOUNTERS);
	REGISTER_FUNC(Export_FBuildGlobals_HACK_HEADER_GENERATOR);
	REGISTER_FUNC(Export_FBuildGlobals_WITH_AUTOMATION_WORKER);
	REGISTER_FUNC(Export_FBuildGlobals_UE_BUILD_MINIMAL);
	REGISTER_FUNC(Export_FBuildGlobals_IS_MONOLITHIC);
	REGISTER_FUNC(Export_FBuildGlobals_IS_PROGRAM);
	REGISTER_FUNC(Export_FBuildGlobals_WITH_HOT_RELOAD);
	REGISTER_FUNC(Export_FBuildGlobals_CHECK_PUREVIRTUALS);
	REGISTER_FUNC(Export_FBuildGlobals_USE_NULL_RHI);
	REGISTER_FUNC(Export_FBuildGlobals_USE_LOGGING_IN_SHIPPING);
	REGISTER_FUNC(Export_FBuildGlobals_USE_CHECKS_IN_SHIPPING);
	REGISTER_FUNC(Export_FBuildGlobals_DO_GUARD_SLOW);
	REGISTER_FUNC(Export_FBuildGlobals_DO_CHECK);
	REGISTER_FUNC(Export_FBuildGlobals_STATS);
	REGISTER_FUNC(Export_FBuildGlobals_ALLOW_DEBUG_FILES);
	REGISTER_FUNC(Export_FBuildGlobals_NO_LOGGING);
	REGISTER_FUNC(Export_FBuildGlobals_LOOKING_FOR_PERF_ISSUES);
	REGISTER_FUNC(Export_FBuildGlobals_USE_NETWORK_PROFILER);
	REGISTER_FUNC(Export_FBuildGlobals_USE_UBER_GRAPH_PERSISTENT_FRAME);
	REGISTER_FUNC(Export_FBuildGlobals_UE_BLUEPRINT_EVENTGRAPH_FASTCALLS);
	REGISTER_FUNC(Export_FBuildGlobals_USE_SERVER_PERF_COUNTERS);
	REGISTER_FUNC(Export_FBuildGlobals_USE_CIRCULAR_DEPENDENCY_LOAD_DEFERRING);
	REGISTER_FUNC(Export_FBuildGlobals_USE_DEFERRED_DEPENDENCY_CHECK_VERIFICATION_TESTS);
	REGISTER_FUNC(Export_FBuildGlobals_ALLOW_PROFILEGPU_IN_TEST);
	REGISTER_FUNC(Export_FBuildGlobals_WITH_PROFILEGPU);
	REGISTER_FUNC(Export_FBuildGlobals_WITH_METADATA);
	REGISTER_FUNC(Export_FBuildGlobals_WITH_SERVER_CODE);
	REGISTER_FUNC(Export_FBuildGlobals_WITH_EDITORONLY_DATA);
	REGISTER_FUNC(Export_FBuildGlobals_WITH_COREUOBJECT);
	REGISTER_FUNC(Export_FBuildGlobals_USE_STATS_WITHOUT_ENGINE);
	REGISTER_FUNC(Export_FBuildGlobals_WITH_LOGGING_TO_MEMORY);
	REGISTER_FUNC(Export_FBuildGlobals_USE_CACHE_FREED_OS_ALLOCS);
	REGISTER_FUNC(Export_FBuildGlobals_WITH_CEF3);
	REGISTER_FUNC(Export_FBuildGlobals_WITH_XGE_CONTROLLER);
	REGISTER_FUNC(Export_FBuildGlobals_WITH_DEV_AUTOMATION_TESTS);
	REGISTER_FUNC(Export_FBuildGlobals_WITH_PERF_AUTOMATION_TESTS);
	REGISTER_FUNC(Export_FBuildGlobals_ENGINE_MAJOR_VERSION);
	REGISTER_FUNC(Export_FBuildGlobals_ENGINE_MINOR_VERSION);
	REGISTER_FUNC(Export_FBuildGlobals_ENGINE_PATCH_VERSION);
}